name: Node.js Package
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: |
          npm i
          npm run deploy-storybook -- --ci
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}